create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text check (char_length(display_name) <= 80),
  avatar_url text check (char_length(avatar_url) <= 2048),
  preferred_os text check (preferred_os is null or preferred_os in ('macos', 'windows', 'linux', 'other')),
  ram_gb smallint check (ram_gb is null or ram_gb between 1 and 4096),
  gpu_name text check (char_length(gpu_name) <= 120),
  gpu_memory_gb numeric(7, 2) check (gpu_memory_gb is null or gpu_memory_gb between 0 and 4096),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.saved_models (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  model_slug text not null check (
    char_length(model_slug) between 1 and 200
    and model_slug ~ '^[A-Za-z0-9][A-Za-z0-9._/-]*$'
  ),
  model_name text not null check (char_length(model_name) between 1 and 200),
  selected_tag text not null default 'latest' check (
    char_length(selected_tag) between 1 and 120
    and selected_tag ~ '^[A-Za-z0-9][A-Za-z0-9._-]*$'
  ),
  personal_note text not null default '' check (char_length(personal_note) <= 4000),
  saved_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, model_slug)
);

create index saved_models_user_saved_at_idx
  on public.saved_models (user_id, saved_at desc);

alter table public.profiles enable row level security;
alter table public.saved_models enable row level security;

create policy profiles_select_own
  on public.profiles
  for select
  to authenticated
  using ((select auth.uid()) = id);

create policy profiles_insert_own
  on public.profiles
  for insert
  to authenticated
  with check ((select auth.uid()) = id);

create policy profiles_update_own
  on public.profiles
  for update
  to authenticated
  using ((select auth.uid()) = id)
  with check ((select auth.uid()) = id);

create policy profiles_delete_own
  on public.profiles
  for delete
  to authenticated
  using ((select auth.uid()) = id);

create policy saved_models_select_own
  on public.saved_models
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

create policy saved_models_insert_own
  on public.saved_models
  for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

create policy saved_models_update_own
  on public.saved_models
  for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create policy saved_models_delete_own
  on public.saved_models
  for delete
  to authenticated
  using ((select auth.uid()) = user_id);

revoke all on public.profiles from anon;
revoke all on public.saved_models from anon;
grant select, insert, update, delete on public.profiles to authenticated;
grant select, insert, update, delete on public.saved_models to authenticated;
grant usage, select on sequence public.saved_models_id_seq to authenticated;

create function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

create trigger saved_models_set_updated_at
before update on public.saved_models
for each row execute function public.set_updated_at();

create function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, display_name, avatar_url)
  values (
    new.id,
    coalesce(
      nullif(new.raw_user_meta_data ->> 'full_name', ''),
      nullif(new.raw_user_meta_data ->> 'name', ''),
      nullif(split_part(coalesce(new.email, ''), '@', 1), '')
    ),
    coalesce(
      nullif(new.raw_user_meta_data ->> 'avatar_url', ''),
      nullif(new.raw_user_meta_data ->> 'picture', '')
    )
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'avatars',
  'avatars',
  true,
  2097152,
  array['image/jpeg', 'image/png', 'image/webp', 'image/gif']
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create policy avatars_insert_own_folder
  on storage.objects
  for insert
  to authenticated
  with check (
    bucket_id = 'avatars'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

create policy avatars_select_own_folder
  on storage.objects
  for select
  to authenticated
  using (
    bucket_id = 'avatars'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

create policy avatars_update_own_folder
  on storage.objects
  for update
  to authenticated
  using (
    bucket_id = 'avatars'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  )
  with check (
    bucket_id = 'avatars'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

create policy avatars_delete_own_folder
  on storage.objects
  for delete
  to authenticated
  using (
    bucket_id = 'avatars'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

comment on table public.profiles is 'Private ailocal.click preferences owned by one authenticated user.';
comment on table public.saved_models is 'Private per-user Ollama model library, tags, and notes.';
